#!/bin/sh

if [ "$(uci -q get luci.diag)" != "internal" ]; then
	host=""

	if [ -s /etc/os-release ]; then
		. /etc/os-release
		host="${HOME_URL:-${BUG_URL:-$LEDE_DEVICE_MANUFACTURER_URL}}"
		host="${host#*://}"
		host="${host%%/*}"
	fi

	uci -q batch <<-EOF >/dev/null
		set luci.diag=internal
		set luci.diag.dns='${host:-openwrt.org}'
		set luci.diag.ping='${host:-openwrt.org}'
		set luci.diag.route='${host:-openwrt.org}'
		commit luci
	EOF
fi

uci -q batch <<-EOF >/dev/null
	del ucitrack.@ssh[-1]
	add ucitrack ssh
	set ucitrack.@ssh[-1].exec="/etc/init.d/sshd restart"
	commit ucitrack
EOF

rm -rf /tmp/luci-*
exit 0
